spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://fcortezb2:MF9MmwzglrDBgY3f@induct3d.aomakv1.mongodb.net/induct3d_db?retryWrites=true&w=majority&appName=Induct3d

email.sender=""
email.password=""

# security
jwt.secret=secretsecretsecretsecretsecretsecretsecretsecret
jwt.expiration=36000
