spring.application.name=backend

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=induct3d_db

email.sender=""
email.password=""

cloudinary.cloud-name=dcaklppjz
cloudinary.api-key=296691738629773
cloudinary.api-secret=JIptkYCBx_BHu8fXxeNsLYfFysY

# security
jwt.secret=secretsecretsecretsecretsecretsecretsecretsecret
jwt.expiration=36000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG