spring.application.name=backend

spring.data.mongodb.uri=${MONGODB_URI}

email.sender=""
email.password=""

# security
jwt.secret=secretsecretsecretsecretsecretsecretsecretsecret
jwt.expiration=36000
